inherit_from: ../vqdif/shapenet_res16.yaml
datamodule_opt:
  class: shapeformer.datamodule.DataModule
  kwargs:
    test_batch_size: 1
    testset_opt:
      class: shapeformer.data.paper_datasets.paper_dataset.npyDataset
      kwargs:
        dlist: configs/demo/demo.lst
        subsample: False
callbacks:
  vis_recon:
    class: shapeformer.models.vqdif.vqdif.VisSparseRecon3D
    kwargs:
      no_sanity_check: True
      every_n_epoch: 5
      quant_grid_depth: 4
      max_length: 512
      vocab_size: 4096
      end_tokens: [4096,4096]
      visual_indices: [0,1,2,3,4,5,6,7,8]
