inherit_from: ../shapeformer/shapenet_scale.yaml
datamodule_opt:
  class: shapeformer.datamodule.DataModule
  kwargs:
    test_batch_size: 1
    testset_opt:
      class: shapeformer.data.paper_datasets.paper_dataset.npyDataset
      kwargs:
        dlist: configs/demo/demo.lst
        subsample: False
callbacks:
  vis_recon:
    class: shapeformer.models.shapeformer.shapeformer.VisShapeFormer
    kwargs:
      data_dir: experiments/demo_shapeformer/

      no_sanity_check: True
      every_n_epoch: 4
      end_tokens: [4096, 4096]

      top_k: 100
      top_p: 0.4
      depth: 4

      resolution: [256,256]
      render_samples: 32
      visual_indices: [0,111111,222222,333333,444444,555555,666666,777777]
